Added Rubocop to the project
wolox-training/gr-rails pull request #3
Opened 2018-02-22 14:56 UTC by gastonrod

## Summary

Added rubocop to the project, and made sure there were no offenses found

## Trello card 

https://trello.com/c/8CuQLsSv/8-configurar-rubocop

2018-02-22 16:14 UTC, icoluccio requested changes

2018-02-22 16:14 UTC, icoluccio commented on Gemfile
> +gem 'rubocop', '~> 0.52.1'
A good practice is to include a description of the gem for each gem you add. You could use the official description (something from https://rubygems.org/gems/rubocop/versions/0.39.0) or something like `linter`

2018-02-22 17:02 UTC, gastonrod commented
Done

2018-02-23 17:35 UTC, icoluccio approved these changes

2018-02-28 12:26 UTC, merged